import Head from "next/head";
import SponsorsTable from "../../components/tables/SponsorsTable";
import Layout from "../../components/Layout";
import { useGetAllSponsorsQuery } from "../../store/services/sponsor";

export default function SponsorListPage() {
  const { data: sponsors = [], isLoading } = useGetAllSponsorsQuery();
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SponsorsTable data={sponsors} isLoading={isLoading} mainView={true} />
    </div>
  );
}
SponsorListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
