import Head from "next/head";
import Layout from "../../components/Layout";
import RewardsTable from "../../components/tables/RewardsTable";
import { useGetAllRewardsQuery } from "../../store/services/reward";

export default function SponsorListPage() {
  const { data: rewards = [], isLoading } = useGetAllRewardsQuery({});

  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RewardsTable data={rewards} isLoading={isLoading} mainView={true} />
    </div>
  );
}
SponsorListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
