steps:
  # Docker build
  - id: "Build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/chatgpt-api-$BRANCH_NAME:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/chatgpt-api-service:latest",
        "--file",
        "Dockerfile.chatgpt-api",
        "--build-arg",
        "project_name=$PROJECT_ID",
        "--build-arg",
        "openai_api_key=$_OPENAI_API_KEY",                
        ".",
      ]
  # Docker push
  - id: "Push docker image to container registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/chatgpt-api-$BRANCH_NAME:$COMMIT_SHA"]
  # Run service
  - id: "Create cloud run service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "chatgpt-api-service",
        "--image",
        "gcr.io/$PROJECT_ID/chatgpt-api-$BRANCH_NAME:$COMMIT_SHA",
        "--region",
        "$_DEPLOY_REGION",
        "--set-env-vars",
        "GOOGLE_CLOUD_PROJECT=$PROJECT_ID",
        "--set-env-vars",
        "OPENAI_API_KEY=$_OPENAI_API_KEY",
        "--set-env-vars",
        "FIREBASE_API_KEY=$_FIREBASE_API_KEY",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/chatgpt-api-service:latest
