steps:
  # Docker build
  - id: "Build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/app-api-$BRANCH_NAME:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/app-api-service:latest",
        "--file",
        "Dockerfile.app-api",
        "--build-arg",
        "project_name=$PROJECT_ID",
        "--build-arg",
        "mining_api=$_MINING_API",
        "--build-arg",
        "openai_api_key=$_OPENAI_API_KEY",
        "--build-arg",
        "scrapping_api=$_SCRAPPING_API",
        "--build-arg",
        "files_bucket=$_FILES_BUCKET",
        ".",
      ]
  # Docker push
  - id: "Push docker image to container registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/app-api-$BRANCH_NAME:$COMMIT_SHA"]
  # Run service
  - id: "Create cloud run service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "app-api-service",
        "--image",
        "gcr.io/$PROJECT_ID/app-api-$BRANCH_NAME:$COMMIT_SHA",
        "--region",
        "$_DEPLOY_REGION",
        "--allow-unauthenticated",
        "--set-env-vars",
        "GOOGLE_CLOUD_PROJECT=$PROJECT_ID",
        "--set-env-vars",
        "SCRAPPER_API_URL=$_SCRAPPING_API",
        "--set-env-vars",
        "MINER_API_URL=$_MINING_API",
        "--set-env-vars",
        "OPENAI_API_KEY=$_OPENAI_API_KEY",
        "--set-env-vars",
        "GOOGLE_CHAT_MESSAGE_SERVICE_KEY=$_CHAT_KEY",
        "--set-env-vars",
        "GOOGLE_CHAT_MESSAGE_SERVICE_TOKEN=$_CHAT_TOKEN",
        "--set-env-vars",
        "FIREBASE_API_KEY=$_FIREBASE_API_KEY",
        "--set-env-vars",
        "FILES_BUCKET=$_FILES_BUCKET",
      ]
  - id: "Print environment variables"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "echo"
    args:
      [
        "Files Bucket: $_FILES_BUCKET",
        "Scrapping API: $_SCRAPPING_API",
        "Mining API: $_MINING_API",
        "OpenAI API Key: $_OPENAI_API_KEY",
      ]
images:
  - gcr.io/$PROJECT_ID/app-api-service:latest
