ARG project_name
ARG scrapping_api
ARG mining_api

FROM node:18-alpine AS base
RUN apk update && apk add git
WORKDIR /app
COPY . .

## Build the app
FROM base as builder
RUN npm ci --workspace app-api
# RUN npm run prebuild -w app-api
RUN npm run build -w app-api

# Start the app
FROM builder as runner

ENV PORT 8000
ENV GOOGLE_CLOUD_PROJECT $project_name
ENV SCRAPPER_API_URL $scrapping_api
ENV MINER_API_URL $mining_api
ENV OPENAI_API_KEY $openai_api_key
ENV FILES_BUCKET=$files_bucket
EXPOSE 8000
CMD ["npm", "run", "start", "-w", "app-api"]
