import Head from "next/head";
import Layout from "../../components/Layout";
import TipsTable from "../../components/tables/TipsTable";
import { useGetAllTipsQuery } from "../../store/services/tip";

export default function TipListPage() {
  const { data: tips = [], isLoading } = useGetAllTipsQuery();
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TipsTable data={tips} isLoading={isLoading} mainView={true} />
    </div>
  );
}
TipListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
