import Head from "next/head";
import Layout from "../../components/Layout";
import UsersTable from "../../components/tables/UsersTable";
import { useGetAllUsersQuery } from "../../store/services/user";

export default function UserListPage() {
  const { data: users = [], isLoading } = useGetAllUsersQuery({});
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UsersTable data={users} isLoading={isLoading} mainView={true} />
    </div>
  );
}
UserListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
