import Head from "next/head";
import { ReactElement } from "react";
import Layout from "../components/Layout";
import router from "next/router";

export default function Home() {
  router.push("/sponsors");

  return (
    <div className="flex flex-1 flex-col items-center justify-center bg-gray-50">
      <Head>
        <title>Bmatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}


Home.getLayout = (page: ReactElement) => {
  return <Layout>{page}</Layout>;
};
