import Head from "next/head";
import { useForm, Controller } from "react-hook-form";
import { Button, InputText, InputPassword, CheckBox } from "ui";
import { useAuth } from "../contexts/AuthContext";
import Image from "next/image";

export default function LoginPage() {
  const { signIn } = useAuth();

  const { handleSubmit, control } = useForm();

  const onSubmit = handleSubmit(async (data) => {
    // todo: handle login errors
    signIn({
      email: data.email,
      password: data.password,
    });
  });

  return (
    <div className="flex flex-1 flex-col min-h-screen">
      <div className="flex w-full items-center justify-between h-16 px-6 bg-white border-b">
        <Image src="/assets/bmatch.svg" unoptimized={true} width={100} height={19} alt="bmatch" />
      </div>
      <div className="flex grow flex-1 flex-col items-center justify-stretch bg-gray-50">
        <Head>
          <title>Bmatch - dev</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="grow flex flex-col items-center justify-center py-12 px-4 w-2/4 sm:px-6 lg:px-8 bg-gray-50">
          <div>
            <h2 className="mt-6 text-center text-gray-500 text-3xl leading-9 font-normal">
              Entrar en la plataforma
            </h2>
            <h6 className="mt-2 mb-8 text-center sm:text-sm text-gray-600 text-sm leading-5 font-normal">
              Introduzca sus datos de usuario para acceder a Bmatch.
            </h6>
          </div>
          <div
            className={`max-w-md w-full space-y-6 px-4 py-8 shadow-md rounded-md bg-white mb-16`}
          >
            <form onSubmit={onSubmit} className="space-y-7 mx-10">
              <Controller
                control={control}
                name="email"
                defaultValue=""
                rules={{
                  required: {
                    value: true,
                    message: "Este campo es obligatorio",
                  },
                }}
                render={({
                  field: { onChange, onBlur, value },
                  fieldState: { error },
                }) => (
                  <InputText
                    id="email"
                    label="Email"
                    value={value}
                    onChange={onChange}
                    onBlur={onBlur}
                    error={error?.message}
                  />
                )}
              />
              <Controller
                control={control}
                name="password"
                defaultValue=""
                rules={{
                  required: {
                    value: true,
                    message: "Este campo es obligatorio",
                  },
                }}
                render={({
                  field: { onChange, onBlur, value },
                  fieldState: { error },
                }) => (
                  <InputPassword
                    id="password"
                    label="Contraseña"
                    value={value}
                    onChange={onChange}
                    onBlur={onBlur}
                    error={error?.message}
                  />
                )}
              />
              <div className="flex flex-row justify-between">
                <Controller
                  control={control}
                  name="keepSession"
                  defaultValue={false}
                  render={({ field: { onChange, value } }) => (
                    <CheckBox
                      id="keepSession"
                      name="keepSession"
                      label="Recordarme"
                      value={value}
                      onChange={onChange}
                    />
                  )}
                />
                <p
                  className="text-sm  text-blue-600 cursor-pointer"
                  role="button"
                  onClick={() => {}}
                >
                  ¿Olvidaste tu contraseña?
                </p>
              </div>
              <Button
                template="bmatch-primary"
                label="Acceder"
                type="submit"
                onClick={onSubmit}
                customClassName="w-full"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
