steps:
  # Docker build
  - id: "Build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/batch-job-$BRANCH_NAME:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/batch-job:latest",
        "--file",
        "apps/batch/Dockerfile.batch-job",
        "--build-arg",
        "project_name=$_PROJECT_ID",
        ".",
      ]
  # Docker push
  - id: "Push docker image to container registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/batch-job-$BRANCH_NAME:$COMMIT_SHA"]
images:
  - gcr.io/$PROJECT_ID/batch-job:latest
