ARG project_name

FROM node:16-alpine AS base
RUN apk update && apk add git
WORKDIR /app
COPY . .

## Build the app
FROM base as builder
RUN npm ci --workspace batch
# RUN npm run prebuild -w batch
RUN npm run build:server -w batch

# Start the app
FROM builder as runner

ENV PORT 8080
ENV GOOGLE_CLOUD_PROJECT=$project_name
EXPOSE 8080
CMD ["npm", "run", "start:server", "-w", "batch"]
