import Head from "next/head";
import Layout from "../../components/Layout";
import GoalsTable from "../../components/tables/GoalsTable";
import { useGetAllGoalsQuery } from "../../store/services/goal";

export default function GoalListPage() {
  const { data: goals = [], isLoading } = useGetAllGoalsQuery();
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GoalsTable data={goals} isLoading={isLoading} mainView={true} />
    </div>
  );
}
GoalListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
