import Head from "next/head";
import Layout from "../../components/Layout";
import { useGetAllServicesQuery } from "../../store/services/service";
import ServiceTable from "../../components/tables/ServiceTable";

export default function ServiceListPage() {
  const { data: services = [], isLoading } = useGetAllServicesQuery();
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ServiceTable data={services} isLoading={isLoading} mainView={true} />
    </div>
  );
}
ServiceListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
