import Head from "next/head";
import Layout from "../../components/Layout";
import { useGetAllInsightsQuery } from "../../store/services/insight";
import InsightsTable from "../../components/tables/InsightsTable";

export default function InsightListPage() {
  const { data: insight = [], isLoading } = useGetAllInsightsQuery();
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InsightsTable data={insight} isLoading={isLoading} mainView={true} />
    </div>
  );
}
InsightListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
