ARG project_name

FROM node:16-alpine AS base
RUN apk update && apk add git
WORKDIR /app
COPY . .

## Build the app
FROM base as builder
RUN npm ci --workspace data-jobs
RUN npm run prebuild -w data-jobs
RUN npm run build -w data-jobs

# Start the app
FROM builder as runner

ENV GOOGLE_CLOUD_PROJECT $project_name
CMD ["npm", "run", "start", "-w", "data-jobs"]
