import Head from "next/head";
import CommunitiesTable from "../../components/tables/CommunitiesTable";
import Layout from "../../components/Layout";
import { useGetAllCommunitiesQuery } from "../../store/services/community";

export default function SponsorListPage() {
  const { data: communities = [], isLoading } = useGetAllCommunitiesQuery({});
  return (
    <div className="flex flex-1 flex-col items-center justify-start bg-gray-50 w-full h-screen">
      <Head>
        <title>Bmatch - dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommunitiesTable
        data={communities}
        isLoading={isLoading}
        mainView={true}
      />
    </div>
  );
}
SponsorListPage.getLayout = (page: JSX.Element) => {
  return <Layout>{page}</Layout>;
};
